### ISSUE TITLE
Hex package v1.1.4 contains priv/k6_bytea.so compiled for mac

### ISSUE THREAD

**Issue by starstuck** [dalmatinerdb/k6_bytea#1]
I makes packaged module not load properly on any other architecture.

**Comment by Licenser** [comment]
Good catch, the hex publishing plugin is very inclusive, slipped my net that it added the compiled binary.

**Comment by Licenser** [comment]
1.1.5 published

**Comment by starstuck** [comment]
Thank you for sorting this one so quickly.
